import React, { useEffect, useState } from 'react';
import {
  FileSearch,
  Search,
  RefreshCw,
  Sparkles,
  Building2,
  Calendar,
  Eye,
  X,
  Target,
} from 'lucide-react';
import { fetchAuditResponses } from '../../lib/adminData';
import { AuditResponse } from '../../types';
import { AIOpportunityReportModal } from './AIOpportunityReportModal';

export function AdminAudits() {
  const [audits, setAudits] = useState<AuditResponse[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedAudit, setSelectedAudit] = useState<AuditResponse | null>(null);

  const loadAudits = async () => {
    setIsLoading(true);
    const res = await fetchAuditResponses();
    setAudits(res.audits);
    setIsLoading(false);
  };

  useEffect(() => {
    loadAudits();
  }, []);

  const filteredAudits = audits.filter((audit) => {
    const term = searchTerm.toLowerCase();
    const company = audit.business?.company_name || '';
    const desc = audit.description || audit.business?.description || '';
    const goal = audit.primary_goal || '';
    const painStr = (audit.pain_points || []).join(' ');
    const toolStr = (audit.current_tools || []).join(' ');

    return (
      company.toLowerCase().includes(term) ||
      desc.toLowerCase().includes(term) ||
      goal.toLowerCase().includes(term) ||
      painStr.toLowerCase().includes(term) ||
      toolStr.toLowerCase().includes(term)
    );
  });

  return (
    <div className="space-y-6 animate-fadeIn">
      {/* Top Controls */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4 bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-teal-500/10 text-teal-700 rounded-xl border border-teal-200">
            <FileSearch className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-[#0A292C]">AI Audit Submissions</h2>
            <p className="text-xs text-slate-500">
              Interactive AI Opportunity Scanner responses generated by potential clients
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {/* Search Box */}
          <div className="relative flex-1 sm:w-64">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-3" />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search audits..."
              className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-300 rounded-xl text-xs text-slate-900 focus:outline-none focus:ring-2 focus:ring-[#F05323]"
            />
          </div>

          <button
            onClick={loadAudits}
            disabled={isLoading}
            className="p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 text-slate-600 transition-colors cursor-pointer"
            title="Refresh Audits"
          >
            <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Audits Table */}
      <div className="bg-white rounded-2xl border border-slate-200/90 shadow-xs overflow-hidden">
        {isLoading ? (
          <div className="p-8 text-center space-y-3">
            <div className="w-6 h-6 border-2 border-teal-600 border-t-transparent rounded-full animate-spin mx-auto" />
            <p className="text-xs font-semibold text-slate-500">Loading AI audits...</p>
          </div>
        ) : filteredAudits.length === 0 ? (
          <div className="p-12 text-center">
            <FileSearch className="w-10 h-10 text-slate-300 mx-auto mb-3" />
            <h3 className="text-sm font-bold text-slate-700">No AI audits found</h3>
            <p className="text-xs text-slate-500 mt-1">
              {searchTerm ? 'Try adjusting your search query.' : 'No audit responses generated yet.'}
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50 border-b border-slate-200 text-slate-500 uppercase tracking-wider font-mono font-bold text-[10px]">
                <tr>
                  <th className="py-3.5 px-4">Business</th>
                  <th className="py-3.5 px-4">Primary Goal</th>
                  <th className="py-3.5 px-4">Pain Points</th>
                  <th className="py-3.5 px-4">Current Tools</th>
                  <th className="py-3.5 px-4">Date</th>
                  <th className="py-3.5 px-4 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-slate-700 font-medium">
                {filteredAudits.map((audit, idx) => {
                  const companyName = audit.business?.company_name || 'Anonymous Business';
                  return (
                    <tr
                      key={audit.id ? `audit-${audit.id}` : `audit-idx-${idx}`}
                      onClick={() => setSelectedAudit(audit)}
                      className="hover:bg-slate-50/80 transition-colors group cursor-pointer"
                    >
                      <td className="py-3.5 px-4 font-bold text-[#0A292C] group-hover:text-[#F05323]">
                        {companyName}
                        {audit.business?.industry && (
                          <span className="block text-[10px] text-slate-400 font-normal">
                            {audit.business.industry}
                          </span>
                        )}
                      </td>
                      <td className="py-3.5 px-4 font-medium text-teal-900 max-w-xs truncate">
                        {audit.primary_goal || 'Process Automation'}
                      </td>
                      <td className="py-3.5 px-4">
                        <div className="flex flex-wrap gap-1 max-w-xs">
                          {audit.pain_points && audit.pain_points.length > 0 ? (
                            audit.pain_points.map((p, idx) => (
                              <span
                                key={idx}
                                className="px-2 py-0.5 bg-rose-50 text-rose-800 border border-rose-200 text-[10px] rounded font-medium"
                              >
                                {p}
                              </span>
                            ))
                          ) : (
                            <span className="text-slate-400 text-[10px]">None</span>
                          )}
                        </div>
                      </td>
                      <td className="py-3.5 px-4">
                        <div className="flex flex-wrap gap-1 max-w-xs">
                          {audit.current_tools && audit.current_tools.length > 0 ? (
                            audit.current_tools.map((t, idx) => (
                              <span
                                key={idx}
                                className="px-2 py-0.5 bg-slate-100 text-slate-700 border border-slate-200 text-[10px] rounded font-medium"
                              >
                                {t}
                              </span>
                            ))
                          ) : (
                            <span className="text-slate-400 text-[10px]">None</span>
                          )}
                        </div>
                      </td>
                      <td className="py-3.5 px-4 text-slate-400 font-mono">
                        {audit.created_at ? new Date(audit.created_at).toLocaleDateString() : '—'}
                      </td>
                      <td className="py-3.5 px-4 text-right">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            setSelectedAudit(audit);
                          }}
                          className="px-3 py-1 bg-[#F05323] hover:bg-[#d84419] text-white text-[11px] font-bold rounded-lg transition-colors cursor-pointer inline-flex items-center gap-1.5"
                        >
                          <Eye className="w-3.5 h-3.5" />
                          <span>View Report</span>
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* AI Opportunity Report Modal */}
      {selectedAudit && (
        <AIOpportunityReportModal
          audit={selectedAudit}
          onClose={() => setSelectedAudit(null)}
        />
      )}
    </div>
  );
}
